### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by solidstatebird** [InquisitivePenguin/pystreamer#1]
A license is probably important, unless you're implementing the entire citysynth project ;)
Also, the directions for the viewing computer should be more detailed because the output will most likely be fed into another program.

**Comment by JacksonCoder** [comment]
Yeah, good idea.

**Comment by JacksonCoder** [comment]
Also, what do you mean by output? The video stream?

**Comment by circuitbird** [comment]
Also add `sudo raspi-config` then go to `interfacing options` and navigate to `camera` and enable it.

**Comment by JacksonCoder** [comment]
Good idea, thanks!

**Comment by JacksonCoder** [comment]
You should probably reopen this issue on my pystreamer-http repo, since this repo is not what we are using for CitySynth
